version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "9001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:9002
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
      - WDS_SOCKET_PORT=9001
    depends_on:
      - ai
    networks:
      - app-network

  ai:
    build: ./ai
    ports:
      - "9002:5000"
    volumes:
      - ./ai:/app
    environment:
      - FLASK_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge